# Generated by Django 4.2.1 on 2023-06-01 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_alter_product_favorite_basket_product_basket_piece'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='почта')),
                ('address', models.TextField(default='', max_length=200, verbose_name='Адрес')),
                ('count', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('summ', models.FloatField(default=0, verbose_name='Цена')),
                ('sale', models.FloatField(default=0, verbose_name='Скидка')),
                ('sale_summ', models.FloatField(default=0, verbose_name='Цена со скидкой')),
                ('comment', models.TextField(default='', verbose_name='Коментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('оформлен', 'оформлен'), ('готов', 'готов'), ('доставлен', 'доставлен')], default='оформлен', max_length=300, verbose_name='Статус')),
                ('way_to_get', models.CharField(choices=[('самовывоз', 'самовывоз'), ('доставка', 'доставка')], default='самовывоз', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.color')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.size')),
            ],
            options={
                'unique_together': {('product', 'order', 'color', 'size')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_piece',
            field=models.ManyToManyField(through='main.OrderPiece', to='main.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('way_to_get', 'доставка'), models.Q(('address', ''), _negated=True)), models.Q(('way_to_get', 'самовывоз'), ('address', '')), _connector='OR'), name='way_to_get_address'),
        ),
    ]
