# Generated by Django 4.2.1 on 2023-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_maincategory_category_main_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('data', models.TextField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='contacts_and_media', verbose_name='Изображение')),
            ],
        ),
    ]
