# Generated by Django 4.2.1 on 2023-06-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=8, verbose_name='Размер'),
        ),
    ]
