# Generated by Django 4.2.1 on 2023-06-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_size_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_formatted',
            field=models.TextField(default='0 ₽', max_length=20, verbose_name='Цена (строка)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sale_cost_formatted',
            field=models.TextField(default='0 ₽', max_length=20, verbose_name='Cкидочная_цена (строка)'),
            preserve_default=False,
        ),
    ]
